ead:
  serviceRegistry:
    username: ${SERVICE_REGISTRY_USERNAME}
    password: ${SERVICE_REGISTRY_PASSWORD}
  auth:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
