ead:
  serviceRegistry:
    username: serviceRegistry
    password: ${SERVICE_REGISTRY_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
