server:
  port: ${PORT}
  servlet:
    context-path: '/ead-auth-user/'

spring:
  application:
    name: ead-auth-user-api
  # Banco de dados
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  # RabbitMQ
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

# Circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxAttempts: 3
        waitDuration: 5s

authuser:
  refreshscope:
    name: EadAuthUserApiUpdate

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

# Properties
ead:
  api:
    url:
      courses: http://ead-course-api/ead-course
    path:
      courses: /courses
      users: /users
  broker:
      exchange:
        userEvent: ead.userevent
