server:
  port: ${PORT}
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-api
  # Banco de dados
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  # RabbitMQ
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
